default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: clone_task_development

test:
  <<: *default
  database: clone_task_test

production:
  <<: *default
  database: clone_task_production
  username: clone_task
  password: <%= ENV['CLONE_TASK_DATABASE_PASSWORD'] %>
